@extends('layouts.tms')
@section('title','Report')
@section('content')
@php
    $total = max(1, $statusCounts->sum());
    $statusTones = [
        'TODO' => 'bg-slate-500',
        'IN_PROGRESS' => 'bg-blue-500',
        'SUBMITTED' => 'bg-violet-500',
        'BLOCKED' => 'bg-rose-500',
        'COMPLETED' => 'bg-emerald-500',
        'CANCELLED' => 'bg-slate-300',
    ];
@endphp
<div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-[10px] font-bold tracking-[.15em] text-blue-600 uppercase">Performance intelligence</p><h1 class="mt-1 text-2xl font-extrabold tracking-[-.045em] sm:text-3xl">Report</h1><p class="mt-1 text-xs text-slate-500">Role-scoped analytics backed by live task data.</p></div><a href="{{ route('tms.reports.export', ['from' => $from->format('Y-m-d'), 'to' => $to->format('Y-m-d')]) }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-xs font-bold text-white"><i data-lucide="download" class="size-4"></i>Export CSV</a></div>
<form class="mt-5 flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-3"><label class="grid gap-1 text-[9px] font-bold text-slate-500">From<input type="date" name="from" value="{{ $from->format('Y-m-d') }}" class="h-10 rounded-xl border-slate-200 text-xs"></label><label class="grid gap-1 text-[9px] font-bold text-slate-500">To<input type="date" name="to" value="{{ $to->format('Y-m-d') }}" class="h-10 rounded-xl border-slate-200 text-xs"></label><button class="mt-auto h-10 rounded-xl bg-blue-600 px-5 text-[10px] font-bold text-white">Apply range</button></form>
<div class="mt-5 grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-extrabold">Status distribution</h2><p class="mt-1 text-[9px] text-slate-400">{{ $statusCounts->sum() }} eligible tasks in period</p><div class="mt-6 grid gap-4">@foreach(array_keys($statusTones) as $status)@php($count=(int)($statusCounts[$status]??0))<div><div class="flex justify-between text-[9px] font-semibold"><span>{{ str($status)->replace('_',' ')->title() }}</span><span>{{ $count }} · {{ round($count/$total*100) }}%</span></div><div class="mt-2 h-2 rounded-full bg-slate-100"><div class="h-full rounded-full {{ $statusTones[$status] }}" style="width:{{ round($count/$total*100) }}%"></div></div></div>@endforeach</div></section><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-extrabold">Category performance</h2><p class="mt-1 text-[9px] text-slate-400">Activity and completion by work type</p><div class="mt-5 overflow-x-auto"><table class="w-full min-w-[520px] text-left"><thead><tr class="border-b border-slate-100 text-[8px] font-bold text-slate-400 uppercase"><th class="pb-3">Category</th><th class="pb-3">Assigned</th><th class="pb-3">Completed</th><th class="pb-3">Rate</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($categoryPerformance as $row)<tr><td class="py-3 text-[10px] font-bold">{{ $row->category->name }}</td><td class="py-3 text-[10px]">{{ $row->total }}</td><td class="py-3 text-[10px]">{{ $row->completed }}</td><td class="py-3"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-[8px] font-bold text-emerald-700">{{ round($row->completed/max(1,$row->total)*100) }}%</span></td></tr>@endforeach</tbody></table></div></section></div>
<section class="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><h2 class="text-sm font-extrabold">Business unit performance</h2><p class="mt-1 text-[9px] text-slate-400">Execution across the operating network</p></div><div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach($businessUnitPerformance as $row)<a href="{{ route('tms.tasks.index',['business_unit_id'=>$row->business_unit_id]) }}" class="rounded-xl border border-slate-100 bg-slate-50 p-4"><div class="flex items-center justify-between"><span class="grid size-8 place-items-center rounded-lg bg-white text-blue-600"><i data-lucide="map-pin" class="size-3.5"></i></span><i data-lucide="arrow-up-right" class="size-3.5 text-slate-300"></i></div><p class="mt-4 text-[11px] font-bold">{{ $row->businessUnit->name }}</p><div class="mt-2 flex items-end justify-between"><p class="text-[9px] text-slate-400">{{ $row->completed }} of {{ $row->total }} complete</p><p class="text-sm font-extrabold">{{ round($row->completed/max(1,$row->total)*100) }}%</p></div></a>@endforeach</div></section>
@endsection
