<?php

namespace App\Http\Controllers\Tms;

use App\Http\Controllers\Controller;
use App\Models\TmsUser;
use App\Tms\TaskScopeService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Response;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ReportController extends Controller
{
    public function index(Request $request, TaskScopeService $scope): View
    {
        /** @var TmsUser $actor */
        $actor = $request->attributes->get('tmsUser');
        $request->validate([
            'from' => ['nullable', 'date'],
            'to' => ['nullable', 'date', 'after_or_equal:from'],
        ]);
        $tasks = $scope->tasksFor($actor);
        $from = $request->date('from') ?? now()->subDays(30);
        $to = $request->date('to') ?? now();
        $tasks->whereBetween('planned_at', [$from->copy()->startOfDay(), $to->copy()->endOfDay()]);

        $statusCounts = (clone $tasks)->selectRaw('status, COUNT(*) total')->groupBy('status')->pluck('total', 'status');
        $categoryPerformance = (clone $tasks)->selectRaw('category_id, COUNT(*) total, SUM(CASE WHEN status = ? THEN 1 ELSE 0 END) completed', ['COMPLETED'])->with('category')->groupBy('category_id')->get();
        $businessUnitPerformance = (clone $tasks)->selectRaw('business_unit_id, COUNT(*) total, SUM(CASE WHEN status = ? THEN 1 ELSE 0 END) completed', ['COMPLETED'])->with('businessUnit')->groupBy('business_unit_id')->get();

        return view('tms.reports', compact('statusCounts', 'categoryPerformance', 'businessUnitPerformance', 'from', 'to'));
    }

    public function export(Request $request, TaskScopeService $scope): StreamedResponse
    {
        /** @var TmsUser $actor */
        $actor = $request->attributes->get('tmsUser');
        $request->validate([
            'from' => ['nullable', 'date'],
            'to' => ['nullable', 'date', 'after_or_equal:from'],
        ]);
        $from = $request->date('from');
        $to = $request->date('to');
        $tasks = $scope->tasksFor($actor)
            ->with(['assignee', 'category', 'businessUnit', 'hospital'])
            ->when($from, fn ($query) => $query->where('planned_at', '>=', $from->copy()->startOfDay()))
            ->when($to, fn ($query) => $query->where('planned_at', '<=', $to->copy()->endOfDay()))
            ->orderBy('planned_at')
            ->get();

        return Response::streamDownload(function () use ($tasks, $actor): void {
            $stream = fopen('php://output', 'w');
            fputcsv($stream, ['Task number', 'Title', 'Category', 'Priority', 'Status', 'Business unit', 'Assignee', 'Hospital', 'Planned', 'Due', 'Generated by', 'Exported at']);
            foreach ($tasks as $task) {
                fputcsv($stream, array_map($this->csvCell(...), [$task->task_number, $task->title, $task->category->name, $task->priority, $task->status, $task->businessUnit->name, $task->assignee->name, $task->hospital?->name ?? $task->hospital_name_snapshot, $task->planned_at->format('d M Y, g:i A'), $task->due_at->format('d M Y, g:i A'), $actor->name, now()->format('d M Y, g:i A')]));
            }
            fclose($stream);
        }, 'tms-tasks-'.now()->format('Y-m-d').'.csv', ['Content-Type' => 'text/csv']);
    }

    private function csvCell(mixed $value): mixed
    {
        if (! is_string($value) || ! preg_match('/^[=+\-@\t\r]/u', ltrim($value))) {
            return $value;
        }

        return "'{$value}";
    }
}
