@extends('layouts.tms')
@section('title', isset($task) ? 'Edit task' : 'Create task')
@section('content')
@php
    $editing = isset($task);
    $hospitalOptions = $hospitals->map(fn ($hospital) => ['id' => (string) $hospital->id, 'businessUnitId' => (string) $hospital->business_unit_id, 'label' => $hospital->name.' · '.$hospital->city])->values();
    $assigneeOptions = $assignees->map(fn ($assignee) => ['id' => (string) $assignee->id, 'businessUnitId' => (string) $assignee->default_business_unit_id, 'label' => $assignee->name.' · '.$assignee->role])->values();
@endphp
<div class="mx-auto max-w-5xl"><div class="mb-5 flex items-center justify-between"><div><a href="{{ $editing ? route('tms.tasks.show',$task) : route('tms.tasks.index') }}" class="inline-flex items-center gap-1 text-[10px] font-bold text-slate-500"><i data-lucide="arrow-left" class="size-3.5"></i>Back</a><h1 class="mt-2 text-2xl font-extrabold tracking-[-.045em]">{{ $editing ? 'Edit task' : 'Create a task' }}</h1><p class="mt-1 text-xs text-slate-500">Turn a priority into a clear, accountable action.</p></div><span class="hidden rounded-full bg-blue-50 px-3 py-1.5 text-[9px] font-bold text-blue-700 sm:block">About 30 seconds</span></div>
<form method="POST" action="{{ $editing ? route('tms.tasks.update',$task) : route('tms.tasks.store') }}" x-data="{ businessUnit: @js((string) old('business_unit_id',$task->business_unit_id??$tmsUser->default_business_unit_id)), hospital: @js((string) old('hospital_id',$task->hospital_id??'')), assignee: @js((string) old('assignee_id',$task->assignee_id??request('assignee'))), hospitals: @js($hospitalOptions), assignees: @js($assigneeOptions) }" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">@csrf @if($editing)@method('PATCH')@endif
    <div class="grid divide-y divide-slate-100 lg:grid-cols-2 lg:divide-x lg:divide-y-0">
        <div class="grid gap-6 p-5 sm:p-7">
            <fieldset><legend class="flex items-center gap-2 text-xs font-extrabold"><span class="grid size-6 place-items-center rounded-lg bg-blue-50 text-[9px] text-blue-700">01</span>What needs to happen?</legend><div class="mt-4 grid gap-4"><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Task title<input name="title" value="{{ old('title',$task->title??'') }}" required maxlength="150" class="h-11 rounded-xl border-slate-200 text-xs" placeholder="e.g. Meet procurement head at City Hospital"></label><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Category<select name="category_id" required class="h-11 rounded-xl border-slate-200 text-xs"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((int)old('category_id',$task->category_id??0)===$category->id)>{{ $category->name }}</option>@endforeach</select></label><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Priority<select name="priority" class="h-11 rounded-xl border-slate-200 text-xs">@foreach(['LOW','MEDIUM','HIGH','URGENT'] as $priority)<option value="{{ $priority }}" @selected(old('priority',$task->priority??'MEDIUM')===$priority)>{{ str($priority)->title() }}</option>@endforeach</select></label></div><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Instructions<textarea name="description" rows="4" maxlength="5000" class="rounded-xl border-slate-200 text-xs" placeholder="Add context, expectations, and useful details…">{{ old('description',$task->description??'') }}</textarea></label></div></fieldset>
            <fieldset><legend class="flex items-center gap-2 text-xs font-extrabold"><span class="grid size-6 place-items-center rounded-lg bg-violet-50 text-[9px] text-violet-700">02</span>Where?</legend><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Business unit<select name="business_unit_id" x-model="businessUnit" @change="hospital = ''; assignee = ''" required class="h-11 rounded-xl border-slate-200 text-xs"><option value="">Select BU</option>@foreach($businessUnits as $unit)<option value="{{ $unit->id }}" @selected((int) old('business_unit_id',$task->business_unit_id??$tmsUser->default_business_unit_id) === $unit->id)>{{ $unit->name }}</option>@endforeach</select></label><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Hospital / account <span class="font-normal text-slate-400">(optional)</span><select name="hospital_id" x-model="hospital" class="h-11 rounded-xl border-slate-200 text-xs"><option value="">None</option><template x-for="option in hospitals.filter(item => item.businessUnitId === businessUnit)" :key="option.id"><option :value="option.id" x-text="option.label"></option></template></select></label></div></fieldset>
        </div>
        <div class="grid content-start gap-6 bg-slate-50/60 p-5 sm:p-7">
            <fieldset><legend class="flex items-center gap-2 text-xs font-extrabold"><span class="grid size-6 place-items-center rounded-lg bg-emerald-50 text-[9px] text-emerald-700">03</span>Who owns it?</legend><div class="mt-4 grid gap-4"><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Assignee<select name="assignee_id" x-model="assignee" required class="h-11 rounded-xl border-slate-200 bg-white text-xs"><option value="">Select assignee</option><template x-for="option in assignees.filter(item => item.businessUnitId === businessUnit)" :key="option.id"><option :value="option.id" x-text="option.label"></option></template></select></label></div></fieldset>
            <fieldset><legend class="flex items-center gap-2 text-xs font-extrabold"><span class="grid size-6 place-items-center rounded-lg bg-amber-50 text-[9px] text-amber-700">04</span>When?</legend><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Planned date & time<input type="datetime-local" name="planned_at" value="{{ old('planned_at',isset($task)?$task->planned_at->format('Y-m-d\TH:i'):now()->format('Y-m-d\TH:i')) }}" required class="h-11 rounded-xl border-slate-200 bg-white text-xs"></label><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Due date & time<input type="datetime-local" name="due_at" value="{{ old('due_at',isset($task)?$task->due_at->format('Y-m-d\TH:i'):now()->addDay()->setTime(17,30)->format('Y-m-d\TH:i')) }}" required class="h-11 rounded-xl border-slate-200 bg-white text-xs"></label></div></fieldset>
            <fieldset><legend class="flex items-center gap-2 text-xs font-extrabold"><span class="grid size-6 place-items-center rounded-lg bg-rose-50 text-[9px] text-rose-700">05</span>Completion requirements</legend><div class="mt-4 grid gap-3"><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Expected outcome<textarea name="expected_outcome" rows="2" class="rounded-xl border-slate-200 bg-white text-xs" placeholder="What should success look like?">{{ old('expected_outcome',$task->expected_outcome??'') }}</textarea></label><label class="flex min-h-12 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-[9px] font-bold"><input type="hidden" name="verification_required" value="0"><input type="checkbox" name="verification_required" value="1" @checked((bool)old('verification_required',$task->verification_required??true)) class="rounded border-slate-300 text-blue-600">Require manager verification</label></div></fieldset>
        </div>
    </div>
    <div class="flex flex-col-reverse gap-2 border-t border-slate-200 bg-white px-5 py-4 sm:flex-row sm:items-center sm:justify-end"><a href="{{ $editing ? route('tms.tasks.show',$task) : route('tms.tasks.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-xl px-5 text-xs font-bold text-slate-500">Cancel</a><button class="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-blue-600 px-6 text-xs font-bold text-white shadow-lg shadow-blue-600/20"><i data-lucide="{{ $editing?'save':'plus' }}" class="size-4"></i>{{ $editing?'Save changes':'Create task' }}</button></div>
</form></div>
@endsection
