@extends('layouts.tms')
@section('title', $task->task_number)
@section('content')
@php
    $statusStyles = ['TODO'=>'bg-slate-100 text-slate-700','IN_PROGRESS'=>'bg-blue-50 text-blue-700','SUBMITTED'=>'bg-violet-50 text-violet-700','COMPLETED'=>'bg-emerald-50 text-emerald-700','BLOCKED'=>'bg-rose-50 text-rose-700','CANCELLED'=>'bg-slate-100 text-slate-400'];
    $isAssignee = $task->assignee_id === $tmsUser->id;
    $canManage = $tmsUser->isRole('GM') || ($tmsUser->isRole('AM') && ($task->assignee->direct_manager_id === $tmsUser->id || $task->created_by_id === $tmsUser->id));
    $completionTitle = $task->verification_required ? 'Submit for verification' : 'Complete task';
    $completionDescription = $task->verification_required ? 'Add the outcome before sending this task to your manager.' : 'Add the outcome before marking this task complete.';
    $completionActionLabel = $task->verification_required ? 'Submit for verification' : 'Complete task';
@endphp
<div x-data="{ completion: false, blocker: false, rework: false }">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('tms.tasks.index') }}" class="inline-flex items-center gap-1 text-[10px] font-bold text-slate-500"><i data-lucide="arrow-left" class="size-3.5"></i>Tasks</a><div class="mt-3 flex flex-wrap items-center gap-2"><span class="rounded-full px-3 py-1 text-[8px] font-bold {{ $statusStyles[$task->status] }}">{{ str($task->status)->replace('_',' ') }}</span>@if($task->isOverdue())<span class="rounded-full bg-rose-600 px-3 py-1 text-[8px] font-bold text-white">OVERDUE</span>@endif<span class="text-[9px] font-semibold text-slate-400">{{ $task->task_number }}</span></div><h1 class="mt-3 max-w-4xl text-2xl font-extrabold tracking-[-.045em] sm:text-3xl">{{ $task->title }}</h1><p class="mt-2 text-xs text-slate-500">{{ $task->category->name }} · {{ $task->businessUnit->name }}</p></div>@if($canManage && $task->status==='TODO')<a href="{{ route('tms.tasks.edit',$task) }}" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold"><i data-lucide="pencil" class="size-4"></i>Edit task</a>@endif</div>

    <div class="mt-6 grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
        <div class="grid gap-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="grid gap-5 sm:grid-cols-2"><div><p class="text-[9px] font-bold tracking-[.12em] text-slate-400 uppercase">Instructions</p><p class="mt-3 whitespace-pre-line text-xs leading-6 text-slate-600">{{ $task->description ?: 'No additional instructions provided.' }}</p></div><div class="rounded-2xl bg-slate-50 p-4"><p class="text-[9px] font-bold tracking-[.12em] text-slate-400 uppercase">Expected outcome</p><p class="mt-3 text-xs leading-5 text-slate-600">{{ $task->expected_outcome ?: 'Capture a clear outcome and next action.' }}</p></div></div></section>
            @if($task->outcome || $task->completion_notes || $task->blocker_reason)<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-extrabold">Execution update</h2><div class="mt-4 grid gap-4 sm:grid-cols-2">@if($task->outcome)<div><p class="text-[9px] font-bold text-slate-400 uppercase">Outcome</p><p class="mt-2 text-xs leading-5">{{ $task->outcome }}</p></div>@endif @if($task->completion_notes)<div><p class="text-[9px] font-bold text-slate-400 uppercase">Notes</p><p class="mt-2 text-xs leading-5">{{ $task->completion_notes }}</p></div>@endif @if($task->blocker_reason)<div class="rounded-xl bg-rose-50 p-3 sm:col-span-2"><p class="text-[9px] font-bold text-rose-700 uppercase">Current blocker</p><p class="mt-1 text-xs text-rose-800">{{ $task->blocker_reason }}</p></div>@endif</div></section>@endif
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-sm font-extrabold">Collaboration</h2><p class="mt-0.5 text-[9px] text-slate-400">Updates from everyone with access</p></div><i data-lucide="messages-square" class="size-4 text-slate-400"></i></div><form method="POST" action="{{ route('tms.tasks.comments.store',$task) }}" class="mt-4 flex gap-2">@csrf<input name="body" required maxlength="3000" class="h-11 min-w-0 flex-1 rounded-xl border-slate-200 text-xs" placeholder="Add a useful update…"><button class="grid size-11 shrink-0 place-items-center rounded-xl bg-slate-950 text-white" aria-label="Add comment"><i data-lucide="send" class="size-4"></i></button></form><div class="mt-5 grid gap-4">@forelse($task->comments as $comment)<div class="flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-lg text-[8px] font-bold text-white" style="background:{{ $comment->author->avatar_color }}">{{ collect(explode(' ',$comment->author->name))->map(fn($n)=>mb_substr($n,0,1))->take(2)->join('') }}</span><div><div class="flex items-center gap-2"><p class="text-[10px] font-bold">{{ $comment->author->name }}</p><span class="text-[8px] text-slate-400">{{ $comment->created_at->diffForHumans() }}</span></div><p class="mt-1 text-[11px] leading-5 text-slate-600">{{ $comment->body }}</p></div></div>@empty<p class="py-4 text-center text-[10px] text-slate-400">No comments yet.</p>@endforelse</div></section>
        </div>
        <aside class="grid content-start gap-5">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-extrabold">Task details</h2><dl class="mt-5 grid gap-4">@foreach([['Assignee',$task->assignee->name],['Manager',$task->assignee->manager?->name??'—'],['Hospital',$task->hospital?->name??$task->hospital_name_snapshot??'—'],['Planned',$task->planned_at->format('d M Y, g:i A')],['Due',$task->due_at->format('d M Y, g:i A')],['Priority',str($task->priority)->title()],['Created by',$task->creator->name],['Source',str($task->source)->title()]] as [$label,$value])<div class="flex items-start justify-between gap-4 border-b border-slate-100 pb-3 last:border-0 last:pb-0"><dt class="text-[9px] font-semibold text-slate-400">{{ $label }}</dt><dd class="text-right text-[10px] font-bold text-slate-700">{{ $value }}</dd></div>@endforeach</dl></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-extrabold">Timeline</h2><div class="mt-5 grid gap-4">@foreach($task->histories->take(8) as $history)<div class="relative flex gap-3 before:absolute before:bottom-[-16px] before:left-[5px] before:top-3 before:w-px before:bg-slate-200 last:before:hidden"><span class="relative z-10 mt-1 size-3 shrink-0 rounded-full border-[3px] border-white bg-blue-600 ring-1 ring-blue-200"></span><div><p class="text-[9px] font-bold">{{ str($history->to_status)->replace('_',' ')->title() }}</p><p class="mt-1 text-[8px] text-slate-400">{{ $history->changedBy->name }} · {{ $history->created_at->format('d M, g:i A') }}</p>@if($history->reason)<p class="mt-1 text-[9px] text-slate-500">{{ $history->reason }}</p>@endif</div></div>@endforeach</div></section>
        </aside>
    </div>

    <div class="sticky bottom-3 z-20 mt-5 flex flex-wrap items-center justify-end gap-2 rounded-2xl border border-slate-200 bg-white/95 p-3 shadow-xl backdrop-blur">
        @if($isAssignee && $task->status==='TODO')<form method="POST" action="{{ route('tms.tasks.transition',[$task,'START']) }}">@csrf<button class="min-h-11 rounded-xl bg-blue-600 px-5 text-xs font-bold text-white">Start task</button></form>@endif
        @if($isAssignee && in_array($task->status,['TODO','IN_PROGRESS'],true))<button @click="blocker=true" class="min-h-11 rounded-xl border border-rose-200 bg-rose-50 px-5 text-xs font-bold text-rose-700">Report blocker</button>@endif
        @if($isAssignee && $task->status==='BLOCKED')<form method="POST" action="{{ route('tms.tasks.transition',[$task,'UNBLOCK']) }}">@csrf<button class="min-h-11 rounded-xl bg-blue-600 px-5 text-xs font-bold text-white">Resume task</button></form>@endif
        @if($isAssignee && $task->status==='IN_PROGRESS')<button @click="completion=true" class="min-h-11 rounded-xl bg-emerald-600 px-5 text-xs font-bold text-white">{{ $task->verification_required?'Submit completion':'Complete task' }}</button>@endif
        @if($canManage && $task->status==='SUBMITTED')<button @click="rework=true" class="min-h-11 rounded-xl border border-amber-200 bg-amber-50 px-5 text-xs font-bold text-amber-700">Request rework</button><form method="POST" action="{{ route('tms.tasks.transition',[$task,'VERIFY']) }}">@csrf<button class="min-h-11 rounded-xl bg-emerald-600 px-5 text-xs font-bold text-white">Verify & complete</button></form>@endif
        @if($canManage && !in_array($task->status,['CANCELLED'],true))<form method="POST" action="{{ route('tms.tasks.transition',[$task,$task->status==='COMPLETED'?'REOPEN':'CANCEL']) }}">@csrf<button class="min-h-11 rounded-xl border border-slate-200 px-4 text-[10px] font-bold text-slate-500">{{ $task->status==='COMPLETED'?'Reopen':'Cancel' }}</button></form>@endif
    </div>

    @foreach([['completion','SUBMIT',$completionTitle,$completionDescription,$completionActionLabel],['blocker','BLOCK','Report blocker','Explain what is preventing progress so your manager can help.','Report blocker'],['rework','REWORK','Request rework','Tell the assignee exactly what needs to change.','Send rework request']] as [$state,$action,$title,$description,$actionLabel])<div x-show="{{ $state }}" x-cloak x-transition.opacity class="fixed inset-0 z-[70] flex items-end justify-center bg-slate-950/45 p-0 sm:items-center sm:p-5" @click.self="{{ $state }}=false"><form method="POST" action="{{ route('tms.tasks.transition',[$task,$action]) }}" class="w-full max-w-lg rounded-t-2xl bg-white p-5 shadow-2xl sm:rounded-2xl">@csrf<div class="flex items-start justify-between"><div><h2 class="text-base font-extrabold">{{ $title }}</h2><p class="mt-1 text-[10px] leading-4 text-slate-500">{{ $description }}</p></div><button type="button" @click="{{ $state }}=false" class="grid size-9 place-items-center rounded-lg bg-slate-100" aria-label="Close dialog"><i data-lucide="x" class="size-4"></i></button></div>@if($action==='SUBMIT')<div class="mt-5 grid gap-4"><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Outcome<textarea name="outcome" required rows="3" class="rounded-xl border-slate-200 text-xs"></textarea></label><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Completion notes<textarea name="completion_notes" rows="3" class="rounded-xl border-slate-200 text-xs"></textarea></label><div class="grid gap-4 sm:grid-cols-2"><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Person met<input name="person_met" class="h-11 rounded-xl border-slate-200 text-xs"></label><label class="grid gap-1.5 text-[10px] font-bold text-slate-600">Next follow-up<input type="datetime-local" name="follow_up_at" class="h-11 rounded-xl border-slate-200 text-xs"></label></div></div>@elseif($action==='BLOCK')<label class="mt-5 grid gap-1.5 text-[10px] font-bold text-slate-600">Blocker reason<textarea name="blocker_reason" required rows="4" class="rounded-xl border-slate-200 text-xs"></textarea></label>@else<label class="mt-5 grid gap-1.5 text-[10px] font-bold text-slate-600">Rework instructions<textarea name="reason" required rows="4" class="rounded-xl border-slate-200 text-xs"></textarea></label>@endif<button class="mt-5 h-11 w-full rounded-xl bg-slate-950 text-xs font-bold text-white">{{ $actionLabel }}</button></form></div>@endforeach
</div>
@endsection
